php:
  build: .
  links:
    - db
    - selenium
  volumes:
    - .:/var/www
nginx:
  image: nginx:1.9.4
  links:
    - php
  volumes_from:
    - php
  volumes:
    - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
  ports:
    - "80:80"
db:
  image: mongo:latest
  volumes:
    - /mnt/sda1/var/lib/mongo-data:/data/db
  ports:
    - "27017:27017"
selenium:
  image: selenium/standalone-firefox-debug:2.48.2
  ports:
    - "4444:4444"
    - "7055:7055"
    - "5900:5900"